# Generated by Django 4.2.25 on 2025-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("KRW", "KRW"),
                            ("GOLD", "GOLD"),
                            ("USD", "USD"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("buy_price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("buy_date", models.DateField()),
            ],
        ),
    ]
