# Generated by Django 5.2.6 on 2025-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('asset_type', models.CharField(choices=[('KRW', 'Korea Won'), ('GOLD', 'Gold'), ('USD', 'US Dollar'), ('JPY', 'Japan Yen'), ('CNY', 'China Yuan')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buy_date', models.DateField()),
            ],
        ),
    ]
